var data = {
  tableData: [
    {
      serialNumber: 1,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 2,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 3,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 4,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 5,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 6,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 7,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 8,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 9,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
    {
      serialNumber: 10,
      processName: '调动',
      processClass: '调动',
      describe: '人员调动',
      taskTime: '2018-02-28 10:02:38',
      status: ' 正常',
    },
  ],
  multipleSelection: [],
}

export default function () { return data };